### ISSUE TITLE
Vagrant user and group in states

### ISSUE THREAD

**Issue by grandmasterv** [myuen/salt#1]
Hi Mack!

Just started reviewing these states.  I found that you are requiring a user and group of 'vagrant' on many files and folders.  This user and group will not exist on our system.  I believe you should be able to change them to 'root' instead and it should still work on your vagrant box too.  Please try that and let me know if it works in your Vagrant environment.

e.g. 
```
BBMap-extract:
  archive.extracted:
    - name: /usr/local/
    - source: /srv/salt/install/binaries/BBMap_37.36.tar.gz
    - unless: ls /usr/local/BBMap_37.36/bbmap.sh
    - user: vagrant
    - group: vagrant
```
